# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7b0b3d12c5c22699928918d96cf2ad7e27f7265484599c91bb3ca1b7a1339108b1d649dcbb0133a9b34fd901ee86a15e771378a98285a5190670eddf7249b4e

test:
  secret_key_base: 75ac9107409bb8ed65ad560ef8fa61ee9197f644dbd1139953be595e2cb14ef4d2854fcbd3ce4f03f25ec12db7241d469a97043a419c902143444c6bda820093

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
